name: universal_ble_backend
description: "Universal BLE backend"
version: 0.5.2
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/universal_ble_backend

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.3.1
  universal_ble: ^0.21.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
