name: universal_ble_backend
description: "Universal BLE backend"
version: 0.1.0
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/universal_ble_backend

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.0.0
  universal_ble: ^0.13.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
