name: ble_backend_screens
description: "BLE backend screens"
version: 1.2.0
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/ble_backend_screens

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.4.0
  cupertino_icons: ^1.0.8
  permission_handler: ^12.0.1
  device_info_plus: ^12.1.0
  wakelock_plus: ^1.4.0
  jumping_dot: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
