name: flutter_web_bluetooth_backend
description: "Flutter Web Bluetooth backend"
version: 1.2.3
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/flutter_web_bluetooth_backend

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.2.3
  flutter_web_bluetooth: ^0.2.4
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
