name: flutter_web_bluetooth_backend
description: "Flutter Web Bluetooth backend"
version: 1.4.1
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/flutter_web_bluetooth_backend

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.4.0
  flutter_web_bluetooth: ^1.1.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
