name: bluez_backend
description: "BlueZ backend"
version: 0.4.0
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/bluez_backend

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.3.0
  bluez: ^0.8.2
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
