name: ble_backend
description: "BLE backend interfaces"
version: 1.2.3
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/ble_backend

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
