name: flutter_reactive_ble_backend
description: "Flutter reactive BLE backend"
version: 1.3.1
homepage: https://github.com/vovagorodok/ble_backends/tree/main/packages/flutter_reactive_ble_backend

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ble_backend: ^1.3.1
  flutter_reactive_ble: ^5.4.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
